#pragma once

#include <cstdint>

// Forward declarations (automatically generated)
class WindissectOpaque;
class ApplicationLanguagesRegistrar; 
namespace Microsoft { namespace WRL { class Details; } } 
class ApplicationLanguages; class ApplicationLanguagesRegistrar; class Bcp47; class CoTaskMemFree; class Destroy; class FEATURE_LOGGED_TRAITS; class FEATURE_STATE_CHANGE_SUBSCRIPTION__; class FontFallback; class GlobUserModelAdapter; class GlobUserSettingsProfileNotify; class HINSTANCE__; class HKEY__; class HKL__; class HSTRING__; class HttpAcceptFormatter; class HttpAcceptRegistryValue; class IActivationFactory; class IApplicationLanguagesRegistrar; class IClassFactory; class IProfileNotify; class IRegistryDwordValue; class IRegistryKey; class IRegistryMultiStringValue; class IRegistryStringValue; class IStream; class IUnknown; class IUserLanguagesRegistrar; class InputMethodCiceroOrder; class LanguageBCP47Telemetry; class LanguageBCP47TraceLogging; class LanguageProfileRegistryKey; class LanguageProfileWritableRegistryKey; class LanguageRegistryKey; class LanguageWriteableRegistryKey; class PackageInfoHelper; class PendingUserDisplayLanguage; class PendingUserDisplayLanguageFallbacks; class PendingUserDisplayLanguageRegistryValue; class PreviousUserDisplayLanguageRegistryValue; class ReadOnlyPendingUserDisplayLanguageRegistryValue; class ReadOnlySystemUserLanguages; class ReadOnlySystemUserLanguagesRegistrar; class ReadOnlyUserLanguages; class ReadOnlyUserLanguagesRegistrar; class RegistryDwordValue; class RegistryKey; class RegistryMultiStringValue; class RegistryStringValue; class ReleaseSRWLockExclusive; class SerializedReadOnlyUserLanguages; class SerializedReadOnlyUserLanguagesRegistrar; class SerializedRegistryKey; class SerializedRegistryMultiStringValue; class SerializedRegistryStringValue; class SortOrderRegistryKey; class StartingUserDisplayLanguageRegistryValue; class SystemUserLanguageRegistryValue; class TransientLcids; class UserDisplayLanguageOverride; class UserDisplayLanguageOverrideRegistryValue; class UserLanguage; class UserLanguageRegistryValue; class UserLanguageRegistryValueWritable; class UserLanguages; class UserLocaleFromLanguageProfileOptOutRegistryValue; class UserLocaleFromLanguageProfileOptOutWritableRegistryValue; class WilFailureReport; class WilFailureReportInformation; class WritableUserLanguages; class WritableUserLanguagesRegistrar; class _CONTEXT; class _EXCEPTION_RECORD; class _GUID; class _RO_REGISTRATION_COOKIE; class _RTL_RUN_ONCE; class _RTL_SRWLOCK; class _TP_CALLBACK_INSTANCE; class _TP_TIMER; class __WIL_RTL_FEATURE_USAGE_DATA; class __WIL__WNF_STATE_NAME; class _tlgProvider_t; class _tlgWrapSz; class _tlgWrapperByVal; class lambda_3fdb14453883e86a37ebade6a7a0ebb0; class lambda_70cdabdc68a96a50d428f6377bd7a278; class lambda_7f96eb1dcf99da5daec8c2467d2d5499; class lambda_b70241e9b5ebaad244db3e52d52cab17; class lambda_d809f5cb0554ff2a5d69d76be77eed0a; class thunk; class type_info; class wil_FeatureState; class wil_details_FeatureReportingCache; class wil_details_FeatureStateCache; class wil_details_FeatureUsageSRUM; 
namespace Microsoft { namespace WRL { class Details; class FtmBase; class RuntimeClassFlags; class SimpleClassFactory; } } 
namespace Microsoft { namespace WRL { namespace Wrappers { class HString; class HStringReference; class SRWLock; } } } 
namespace Microsoft { namespace WRL { namespace Wrappers { namespace Details { class SyncLockExclusive; } } } } 
namespace Windows { namespace Internal { class CLanguage; class CRegion; class String; class StringReference; } } 
namespace Windows { namespace Internal { namespace _StringDetail { class dummy_t; } } } 
namespace std { class _Func_base; class _Hash_find_last_result; class _List_node; class _List_simple_types; class _List_unchecked_iterator; class _List_val; class _Simple_types; class _Value_init_tag; class _Vector_const_iterator; class _Vector_iterator; class _Vector_val; class allocator; class back_insert_iterator; class bad_alloc; class bad_array_new_length; class basic_string; class char_traits; class default_delete; class equal_to; class exception; class function; class less; class nothrow_t; class nullptr_t; class pair; class piecewise_construct_t; class reverse_iterator; class shared_ptr; class tuple; class unique_ptr; class vector; } 
namespace wil { class FailureInfo; class ResultException; class process_heap_deleter; class srwlock; class unique_any_t; } 
namespace wil { namespace details { class DestroyThreadPoolTimer; class FeatureStateManager; class ResultStatus; class SystemThreadPoolMethods; class ThreadFailureCallbackHolder; class resource_policy; class unique_storage; } } 
namespace wil { namespace details_abi { class FeatureStateData; class ProcessLocalData; class ProcessLocalStorageData; class RawUsageIndex; class ThreadLocalData; class UsageIndexProperty; class UsageIndexes; class heap_buffer; class heap_vector; } } 
namespace wistd { class function; class integral_constant; class unique_ptr; } 
namespace wistd { namespace __function { class __base; } } 

